# Generated by Django 5.1.12 on 2025-09-26 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_company',
        ),
        migrations.AddField(
            model_name='user',
            name='accessibility_preferences',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='disability',
            field=models.CharField(choices=[('none', 'Ninguna'), ('visual', 'Visual'), ('motor', 'Motor'), ('cognitive', 'Cognitiva'), ('hearing', 'Auditiva')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_captcha',
            field=models.CharField(default='auto', max_length=30),
        ),
    ]
