# Generated by Django 5.1.12 on 2025-09-26 11:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_is_company_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at'], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='accessibility_preferences',
        ),
        migrations.RemoveField(
            model_name='user',
            name='disability',
        ),
        migrations.RemoveField(
            model_name='user',
            name='preferred_captcha',
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de registro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='disability_type',
            field=models.CharField(choices=[('none', 'Sin discapacidad'), ('visual', 'Visual'), ('auditive', 'Auditiva'), ('motor', 'Motriz'), ('cognitive', 'Cognitiva'), ('multiple', 'Múltiple'), ('other', 'Otra'), ('prefer_not_say', 'Prefiero no decirlo')], default='prefer_not_say', help_text='Esta información es confidencial y nos ayuda a mejorar la accesibilidad', max_length=20, verbose_name='Tipo de discapacidad'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False, help_text='Indica si el usuario ha verificado su correo electrónico', verbose_name='Email verificado'),
        ),
        migrations.AddField(
            model_name='user',
            name='high_contrast_mode',
            field=models.BooleanField(default=False, help_text='Activa un tema con mayor contraste para facilitar la lectura', verbose_name='Modo alto contraste'),
        ),
        migrations.AddField(
            model_name='user',
            name='large_text_mode',
            field=models.BooleanField(default=False, help_text='Aumenta el tamaño de la fuente en toda la plataforma', verbose_name='Texto grande'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='Número de contacto del usuario', max_length=20, null=True, verbose_name='Teléfono'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Imagen de perfil del usuario (opcional)', null=True, upload_to='profile_pictures/', verbose_name='Foto de perfil'),
        ),
        migrations.AddField(
            model_name='user',
            name='requires_screen_reader',
            field=models.BooleanField(default=False, help_text='Indica si el usuario utiliza tecnología de lectura de pantalla', verbose_name='Usa lector de pantalla'),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última actualización'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('candidate', 'Candidato'), ('company', 'Empresa'), ('admin', 'Administrador')], default='candidate', help_text='Define si el usuario es un candidato o una empresa', max_length=20, verbose_name='Tipo de usuario'),
        ),
    ]
