# Generated by Django 5.1.12 on 2025-09-26 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-created_at'], 'verbose_name': 'Oferta de trabajo', 'verbose_name_plural': 'Ofertas de trabajo'},
        ),
        migrations.RemoveField(
            model_name='job',
            name='salary',
        ),
        migrations.AddField(
            model_name='job',
            name='accessibility_features',
            field=models.TextField(blank=True, help_text='Describe las adaptaciones y características de accesibilidad disponibles', verbose_name='Características de accesibilidad'),
        ),
        migrations.AddField(
            model_name='job',
            name='application_deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha límite para aplicar'),
        ),
        migrations.AddField(
            model_name='job',
            name='benefits',
            field=models.TextField(blank=True, verbose_name='Beneficios adicionales'),
        ),
        migrations.AddField(
            model_name='job',
            name='disability_focus',
            field=models.CharField(choices=[('visual', 'Discapacidad visual'), ('hearing', 'Discapacidad auditiva'), ('physical', 'Discapacidad física/motriz'), ('cognitive', 'Discapacidad cognitiva'), ('intellectual', 'Discapacidad intelectual'), ('psychosocial', 'Discapacidad psicosocial'), ('multiple', 'Discapacidad múltiple'), ('all', 'Todas las discapacidades')], default='all', max_length=20, verbose_name='Enfoque en discapacidad'),
        ),
        migrations.AddField(
            model_name='job',
            name='experience_level',
            field=models.CharField(choices=[('entry', 'Sin experiencia'), ('junior', 'Junior (1-2 años)'), ('mid', 'Intermedio (3-5 años)'), ('senior', 'Senior (5+ años)')], default='entry', max_length=20, verbose_name='Nivel de experiencia requerido'),
        ),
        migrations.AddField(
            model_name='job',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='Destacar oferta'),
        ),
        migrations.AddField(
            model_name='job',
            name='is_remote',
            field=models.BooleanField(default=False, verbose_name='¿Es trabajo remoto?'),
        ),
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('full_time', 'Tiempo completo'), ('part_time', 'Tiempo parcial'), ('contract', 'Por contrato'), ('internship', 'Prácticas'), ('remote', 'Remoto')], default='full_time', max_length=20, verbose_name='Tipo de empleo'),
        ),
        migrations.AddField(
            model_name='job',
            name='requirements',
            field=models.TextField(default='', help_text='Educación, experiencia y habilidades requeridas', verbose_name='Requisitos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='responsibilities',
            field=models.TextField(default='Responsabilidades por definir', help_text='Describe las tareas y responsabilidades del puesto', verbose_name='Responsabilidades principales'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='salary_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salario máximo'),
        ),
        migrations.AddField(
            model_name='job',
            name='salary_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salario mínimo'),
        ),
        migrations.AddField(
            model_name='job',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(verbose_name='Descripción del trabajo'),
        ),
        migrations.AlterField(
            model_name='job',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='¿Está activa?'),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(max_length=200, verbose_name='Ubicación'),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Título del puesto'),
        ),
    ]
