# Generated by Django 5.1.12 on 2025-10-15 23:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_job_options_remove_job_salary_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Oferta creada'), ('submitted', 'Oferta enviada para revisión'), ('validated', 'Validación realizada'), ('approved', 'Oferta aprobada'), ('rejected', 'Oferta rechazada'), ('changes_requested', 'Cambios solicitados'), ('resubmitted', 'Oferta reenviada'), ('updated', 'Oferta actualizada'), ('deactivated', 'Oferta desactivada')], max_length=20, verbose_name='Acción realizada')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha y hora')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Detalles adicionales')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('notes', models.TextField(blank=True, verbose_name='Notas adicionales')),
            ],
            options={
                'verbose_name': 'Registro de auditoría',
                'verbose_name_plural': 'Registros de auditoría',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='job',
            name='compliance_status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('pending_review', 'Pendiente de revisión'), ('approved', 'Aprobada'), ('rejected', 'Rechazada'), ('changes_requested', 'Cambios solicitados')], default='draft', help_text='Estado de validación de cumplimiento normativo', max_length=20, verbose_name='Estado de cumplimiento legal'),
        ),
        migrations.AddField(
            model_name='job',
            name='non_discrimination_statement',
            field=models.TextField(blank=True, help_text='Declaración explícita de políticas de inclusión y no discriminación (OBLIGATORIO)', verbose_name='Declaración de no discriminación'),
        ),
        migrations.AddField(
            model_name='job',
            name='reasonable_accommodations',
            field=models.TextField(blank=True, help_text='Describe los ajustes razonables que la empresa puede proporcionar (OBLIGATORIO según Ley 1618)', verbose_name='Ajustes razonables disponibles'),
        ),
        migrations.AddField(
            model_name='job',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Motivo por el cual la oferta fue rechazada o requiere cambios', verbose_name='Razón de rechazo'),
        ),
        migrations.AddField(
            model_name='job',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de revisión'),
        ),
        migrations.AddField(
            model_name='job',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_jobs', to=settings.AUTH_USER_MODEL, verbose_name='Revisado por'),
        ),
        migrations.AddField(
            model_name='job',
            name='workplace_accessibility',
            field=models.TextField(blank=True, help_text='Describe las características de accesibilidad física y tecnológica (OBLIGATORIO)', verbose_name='Condiciones de accesibilidad del lugar de trabajo'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['compliance_status'], name='companies_j_complia_6d47ec_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['is_active', 'compliance_status'], name='companies_j_is_acti_80de0b_idx'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='companies.job', verbose_name='Oferta de trabajo'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['job', '-timestamp'], name='companies_a_job_id_7514f2_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', '-timestamp'], name='companies_a_user_id_885cf8_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', '-timestamp'], name='companies_a_action_e5bcde_idx'),
        ),
    ]
