# Generated by Django 5.1.12 on 2025-10-17 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_auditlog_job_compliance_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HiringReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='Nombre de la empresa')),
                ('company_nit', models.CharField(max_length=50, verbose_name='NIT de la empresa')),
                ('contract_number', models.CharField(max_length=100, verbose_name='Número de contrato')),
                ('contract_date', models.DateField(verbose_name='Fecha de contrato')),
                ('position_title', models.CharField(max_length=200, verbose_name='Cargo')),
                ('disability_type', models.CharField(choices=[('type_a', 'Tipo A - Visual'), ('type_b', 'Tipo B - Auditiva'), ('type_c', 'Tipo C - Física/Motriz'), ('type_d', 'Tipo D - Cognitiva'), ('type_e', 'Tipo E - Intelectual'), ('type_f', 'Tipo F - Psicosocial'), ('type_g', 'Tipo G - Múltiple')], max_length=20, verbose_name='Tipo de discapacidad (codificado)')),
                ('disability_percentage', models.IntegerField(blank=True, null=True, verbose_name='Porcentaje de discapacidad')),
                ('status', models.CharField(choices=[('pending', 'Pendiente de envío'), ('sent', 'Enviado'), ('confirmed', 'Confirmado por Ministerio'), ('failed', 'Falló el envío'), ('retry', 'Reintentando')], default='pending', max_length=20, verbose_name='Estado del informe')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='hiring_reports/pdf/%Y/%m/', verbose_name='Archivo PDF')),
                ('xml_file', models.FileField(blank=True, null=True, upload_to='hiring_reports/xml/%Y/%m/', verbose_name='Archivo XML')),
                ('digital_signature', models.TextField(blank=True, help_text='Hash SHA-256 del documento', verbose_name='Firma digital')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de envío')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de confirmación')),
                ('retry_count', models.IntegerField(default=0, verbose_name='Intentos de envío')),
                ('last_retry_at', models.DateTimeField(blank=True, null=True, verbose_name='Último intento')),
                ('ministry_response', models.JSONField(blank=True, default=dict, verbose_name='Respuesta del Ministerio')),
                ('ministry_receipt_number', models.CharField(blank=True, max_length=100, verbose_name='Número de recibo del Ministerio')),
                ('notes', models.TextField(blank=True, verbose_name='Notas adicionales')),
                ('error_log', models.TextField(blank=True, verbose_name='Registro de errores')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hiring_reports', to=settings.AUTH_USER_MODEL, verbose_name='Empresa')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hiring_reports', to='companies.job', verbose_name='Oferta de trabajo')),
            ],
            options={
                'verbose_name': 'Informe de contratación',
                'verbose_name_plural': 'Informes de contratación',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', '-created_at'], name='companies_h_company_fea56f_idx'), models.Index(fields=['status', '-created_at'], name='companies_h_status_9accf7_idx'), models.Index(fields=['contract_number'], name='companies_h_contrac_52de32_idx')],
            },
        ),
    ]
