# Generated by Django 5.1.12 on 2025-10-17 22:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_hiringreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeQuotaTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_employees', models.PositiveIntegerField(default=0, help_text='Número total de empleados en la empresa', verbose_name='Total de empleados')),
                ('employees_with_disability', models.PositiveIntegerField(default=0, help_text='Número de empleados con discapacidad actualmente contratados', verbose_name='Empleados con discapacidad')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quota_tracking', to=settings.AUTH_USER_MODEL, verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Seguimiento de Cuotas',
                'verbose_name_plural': 'Seguimiento de Cuotas',
            },
        ),
        migrations.CreateModel(
            name='QuotaHistoricalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(help_text='Fecha del periodo (primer día del mes)', verbose_name='Periodo')),
                ('total_employees', models.PositiveIntegerField(verbose_name='Total empleados')),
                ('employees_with_disability', models.PositiveIntegerField(verbose_name='Empleados con discapacidad')),
                ('required_employees', models.PositiveIntegerField(verbose_name='Empleados requeridos')),
                ('compliance_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Porcentaje de cumplimiento')),
                ('is_compliant', models.BooleanField(default=False, verbose_name='¿Cumple?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quota_history', to=settings.AUTH_USER_MODEL, verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Registro Histórico de Cuotas',
                'verbose_name_plural': 'Registros Históricos de Cuotas',
                'ordering': ['-period'],
                'unique_together': {('company', 'period')},
            },
        ),
    ]
