# Generated by Django 5.1.12 on 2025-11-21 03:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialSkillsCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título del curso')),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('description', models.TextField(help_text='Descripción detallada del curso', verbose_name='Descripción')),
                ('category', models.CharField(choices=[('communication', 'Comunicación'), ('teamwork', 'Trabajo en Equipo'), ('problem_solving', 'Resolución de Problemas'), ('leadership', 'Liderazgo'), ('conflict_resolution', 'Resolución de Conflictos'), ('time_management', 'Gestión del Tiempo')], default='communication', max_length=50, verbose_name='Categoría')),
                ('difficulty', models.CharField(choices=[('beginner', 'Principiante'), ('intermediate', 'Intermedio'), ('advanced', 'Avanzado')], default='beginner', max_length=20, verbose_name='Nivel de dificultad')),
                ('duration_hours', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Duración (horas estimadas)')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='courses/thumbnails/', verbose_name='Imagen de portada')),
                ('is_active', models.BooleanField(default=True, verbose_name='Curso activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden de visualización')),
            ],
            options={
                'verbose_name': 'Curso de Habilidades Sociales',
                'verbose_name_plural': 'Cursos de Habilidades Sociales',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('enrolled', 'Inscrito'), ('in_progress', 'En Progreso'), ('completed', 'Completado'), ('dropped', 'Abandonado')], default='enrolled', max_length=20, verbose_name='Estado')),
                ('progress_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Progreso (%)')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de inscripción')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de inicio')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de finalización')),
                ('last_accessed_at', models.DateTimeField(auto_now=True, verbose_name='Último acceso')),
                ('certificate_issued', models.BooleanField(default=False, verbose_name='Certificado emitido')),
                ('certificate_number', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Número de certificado')),
                ('candidate', models.ForeignKey(limit_choices_to={'user_type': 'candidate'}, on_delete=django.db.models.deletion.CASCADE, related_name='course_enrollments', to=settings.AUTH_USER_MODEL, verbose_name='Candidato')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='training.socialskillscourse', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Inscripción a Curso',
                'verbose_name_plural': 'Inscripciones a Cursos',
                'ordering': ['-enrolled_at'],
                'unique_together': {('candidate', 'course')},
            },
        ),
        migrations.CreateModel(
            name='CourseLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título de la lección')),
                ('content_type', models.CharField(choices=[('video', 'Video'), ('text', 'Texto/Lectura'), ('quiz', 'Cuestionario'), ('interactive', 'Actividad Interactiva')], default='text', max_length=20, verbose_name='Tipo de contenido')),
                ('content', models.TextField(help_text='Contenido textual o descripción del video', verbose_name='Contenido de la lección')),
                ('video_url', models.URLField(blank=True, help_text='URL del video (simulado - no funcional en esta versión)', null=True, verbose_name='URL del video')),
                ('video_duration_minutes', models.PositiveIntegerField(default=0, help_text='Solo informativo', verbose_name='Duración del video (minutos)')),
                ('transcript', models.TextField(blank=True, help_text='Transcripción del video o contenido adicional para accesibilidad', verbose_name='Transcripción')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden en el curso')),
                ('is_mandatory', models.BooleanField(default=True, verbose_name='Lección obligatoria')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='training.socialskillscourse', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Lección',
                'verbose_name_plural': 'Lecciones',
                'ordering': ['course', 'order'],
                'unique_together': {('course', 'order')},
            },
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False, verbose_name='Completada')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de finalización')),
                ('time_spent_minutes', models.PositiveIntegerField(default=0, verbose_name='Tiempo dedicado (minutos)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to='training.courseenrollment', verbose_name='Inscripción')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='training.courselesson', verbose_name='Lección')),
            ],
            options={
                'verbose_name': 'Progreso de Lección',
                'verbose_name_plural': 'Progreso de Lecciones',
                'unique_together': {('enrollment', 'lesson')},
            },
        ),
    ]
