# Generated by Django 5.1.12 on 2025-11-21 11:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', models.CharField(editable=False, max_length=12, unique=True, verbose_name='Código de seguimiento')),
                ('complaint_type', models.CharField(choices=[('job_offer', 'Oferta de Empleo Discriminatoria'), ('recruitment_process', 'Proceso de Reclutamiento No Inclusivo'), ('workplace_accessibility', 'Falta de Accesibilidad en el Lugar de Trabajo'), ('discrimination', 'Discriminación o Acoso'), ('lack_of_adjustments', 'Negación de Ajustes Razonables'), ('quota_non_compliance', 'Incumplimiento de Cuotas de Empleo'), ('other', 'Otro')], max_length=50, verbose_name='Tipo de denuncia')),
                ('subject', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(10, 'El asunto debe tener al menos 10 caracteres')], verbose_name='Asunto')),
                ('description', models.TextField(help_text='Describa los hechos de manera detallada', validators=[django.core.validators.MinLengthValidator(50, 'La descripción debe tener al menos 50 caracteres')], verbose_name='Descripción detallada')),
                ('company_name', models.CharField(blank=True, max_length=200, verbose_name='Nombre de la empresa')),
                ('job_posting_url', models.URLField(blank=True, verbose_name='URL de la oferta (opcional)')),
                ('is_anonymous', models.BooleanField(default=True, verbose_name='Denuncia anónima')),
                ('complainant_name', models.CharField(blank=True, max_length=200, verbose_name='Nombre del denunciante (opcional)')),
                ('complainant_email', models.EmailField(blank=True, max_length=254, verbose_name='Email del denunciante (opcional)')),
                ('complainant_phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono del denunciante (opcional)')),
                ('evidence_file1', models.FileField(blank=True, help_text='Capturas de pantalla, documentos, etc.', null=True, upload_to='complaints/evidence/%Y/%m/', verbose_name='Evidencia 1 (opcional)')),
                ('evidence_file2', models.FileField(blank=True, null=True, upload_to='complaints/evidence/%Y/%m/', verbose_name='Evidencia 2 (opcional)')),
                ('evidence_file3', models.FileField(blank=True, null=True, upload_to='complaints/evidence/%Y/%m/', verbose_name='Evidencia 3 (opcional)')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('under_review', 'En Revisión'), ('resolved', 'Resuelta'), ('rejected', 'Rechazada')], default='pending', max_length=20, verbose_name='Estado')),
                ('priority', models.IntegerField(choices=[(1, 'Baja'), (2, 'Media'), (3, 'Alta'), (4, 'Urgente')], default=2, verbose_name='Prioridad')),
                ('admin_response', models.TextField(blank=True, verbose_name='Respuesta del administrador')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de resolución')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_complaints', to=settings.AUTH_USER_MODEL, verbose_name='Asignado a')),
                ('complainant_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filed_complaints', to=settings.AUTH_USER_MODEL, verbose_name='Usuario denunciante')),
            ],
            options={
                'verbose_name': 'Denuncia',
                'verbose_name_plural': 'Denuncias',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplaintComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(validators=[django.core.validators.MinLengthValidator(10, 'El comentario debe tener al menos 10 caracteres')], verbose_name='Comentario')),
                ('is_internal', models.BooleanField(default=True, help_text='Solo visible para administradores', verbose_name='Comentario interno')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='complaints.complaint', verbose_name='Denuncia')),
            ],
            options={
                'verbose_name': 'Comentario de Denuncia',
                'verbose_name_plural': 'Comentarios de Denuncias',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplaintStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(choices=[('pending', 'Pendiente'), ('under_review', 'En Revisión'), ('resolved', 'Resuelta'), ('rejected', 'Rechazada')], max_length=20, verbose_name='Estado anterior')),
                ('new_status', models.CharField(choices=[('pending', 'Pendiente'), ('under_review', 'En Revisión'), ('resolved', 'Resuelta'), ('rejected', 'Rechazada')], max_length=20, verbose_name='Nuevo estado')),
                ('reason', models.TextField(blank=True, verbose_name='Razón del cambio')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Cambiado por')),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='complaints.complaint', verbose_name='Denuncia')),
            ],
            options={
                'verbose_name': 'Historial de Estado',
                'verbose_name_plural': 'Historial de Estados',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['tracking_code'], name='complaints__trackin_513965_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['status', '-created_at'], name='complaints__status_f077e8_idx'),
        ),
    ]
