# Generated by Django 5.1.12 on 2025-11-21 12:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, verbose_name='Asunto')),
                ('job_title', models.CharField(blank=True, max_length=200, verbose_name='Oferta de trabajo relacionada')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('candidate_last_read', models.DateTimeField(blank=True, null=True, verbose_name='Última lectura del candidato')),
                ('company_last_read', models.DateTimeField(blank=True, null=True, verbose_name='Última lectura de la empresa')),
                ('is_archived_by_candidate', models.BooleanField(default=False, verbose_name='Archivado por candidato')),
                ('is_archived_by_company', models.BooleanField(default=False, verbose_name='Archivado por empresa')),
                ('candidate', models.ForeignKey(limit_choices_to={'user_type': 'candidate'}, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_conversations', to=settings.AUTH_USER_MODEL, verbose_name='Candidato')),
                ('company', models.ForeignKey(limit_choices_to={'user_type': 'company'}, on_delete=django.db.models.deletion.CASCADE, related_name='company_conversations', to=settings.AUTH_USER_MODEL, verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Conversación',
                'verbose_name_plural': 'Conversaciones',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Contenido del mensaje')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='messaging/attachments/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png', 'txt'])], verbose_name='Archivo adjunto')),
                ('attachment_alt_text', models.CharField(blank=True, help_text='Descripción accesible del archivo adjunto', max_length=500, verbose_name='Texto alternativo del archivo')),
                ('attachment_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tamaño del archivo (bytes)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de envío')),
                ('is_read', models.BooleanField(default=False, verbose_name='Leído')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de lectura')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messaging.conversation', verbose_name='Conversación')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Remitente')),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajes',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False, verbose_name='Leída')),
                ('is_email_sent', models.BooleanField(default=False, verbose_name='Email enviado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='messaging.message', verbose_name='Mensaje')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Notificación de Mensaje',
                'verbose_name_plural': 'Notificaciones de Mensajes',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'message')},
            },
        ),
    ]
