# Generated by Django 5.1.12 on 2025-11-21 12:29

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_title', models.CharField(blank=True, max_length=200, verbose_name='Título del puesto')),
                ('title', models.CharField(help_text='Ej: Entrevista técnica - Desarrollador Frontend', max_length=200, verbose_name='Título de la entrevista')),
                ('description', models.TextField(help_text='Detalles sobre la entrevista, temas a tratar, etc.', verbose_name='Descripción')),
                ('scheduled_date', models.DateField(verbose_name='Fecha programada')),
                ('scheduled_time', models.TimeField(verbose_name='Hora programada')),
                ('duration_minutes', models.PositiveIntegerField(default=60, help_text='Duración estimada de la entrevista', verbose_name='Duración (minutos)')),
                ('interview_type', models.CharField(choices=[('in_person', 'Presencial'), ('online', 'En línea'), ('phone', 'Telefónica'), ('hybrid', 'Híbrida')], default='online', max_length=20, verbose_name='Tipo de entrevista')),
                ('platform', models.CharField(blank=True, choices=[('zoom', 'Zoom'), ('teams', 'Microsoft Teams'), ('meet', 'Google Meet'), ('webex', 'Cisco Webex'), ('other', 'Otra plataforma')], help_text='Solo para entrevistas en línea', max_length=20, verbose_name='Plataforma de reunión')),
                ('meeting_url', models.URLField(blank=True, help_text='Link de Zoom, Teams, Meet, etc.', validators=[django.core.validators.URLValidator()], verbose_name='URL de la reunión')),
                ('meeting_id', models.CharField(blank=True, max_length=100, verbose_name='ID de la reunión')),
                ('meeting_password', models.CharField(blank=True, max_length=100, verbose_name='Contraseña de la reunión')),
                ('location_address', models.TextField(blank=True, help_text='Dirección completa para entrevistas presenciales', verbose_name='Dirección')),
                ('location_instructions', models.TextField(blank=True, help_text='Cómo llegar, piso, oficina, etc.', verbose_name='Instrucciones de ubicación')),
                ('requires_sign_language_interpreter', models.BooleanField(default=False, verbose_name='Requiere intérprete de lengua de señas')),
                ('requires_accessible_location', models.BooleanField(default=False, verbose_name='Requiere ubicación accesible (rampa, ascensor)')),
                ('requires_screen_reader_support', models.BooleanField(default=False, verbose_name='Requiere soporte para lector de pantalla')),
                ('requires_captioning', models.BooleanField(default=False, verbose_name='Requiere subtítulos en tiempo real')),
                ('other_accessibility_needs', models.TextField(blank=True, help_text='Describa cualquier otra necesidad especial', verbose_name='Otras necesidades de accesibilidad')),
                ('company_notes', models.TextField(blank=True, help_text='Notas internas de la empresa sobre el candidato', verbose_name='Notas de la empresa')),
                ('status', models.CharField(choices=[('proposed', 'Propuesta'), ('confirmed', 'Confirmada'), ('cancelled', 'Cancelada'), ('completed', 'Completada'), ('rescheduled', 'Reprogramada')], default='proposed', max_length=20, verbose_name='Estado')),
                ('company_confirmed', models.BooleanField(default=True, verbose_name='Confirmado por empresa')),
                ('candidate_confirmed', models.BooleanField(default=False, verbose_name='Confirmado por candidato')),
                ('cancellation_reason', models.TextField(blank=True, verbose_name='Razón de cancelación')),
                ('company_feedback', models.TextField(blank=True, verbose_name='Comentarios de la empresa')),
                ('candidate_feedback', models.TextField(blank=True, verbose_name='Comentarios del candidato')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_interviews', to=settings.AUTH_USER_MODEL, verbose_name='Cancelado por')),
                ('candidate', models.ForeignKey(limit_choices_to={'user_type': 'candidate'}, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_interviews', to=settings.AUTH_USER_MODEL, verbose_name='Candidato')),
                ('company', models.ForeignKey(limit_choices_to={'user_type': 'company'}, on_delete=django.db.models.deletion.CASCADE, related_name='company_interviews', to=settings.AUTH_USER_MODEL, verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Entrevista',
                'verbose_name_plural': 'Entrevistas',
                'ordering': ['-scheduled_date', '-scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='InterviewNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('created', 'Entrevista creada'), ('confirmed', 'Entrevista confirmada'), ('cancelled', 'Entrevista cancelada'), ('rescheduled', 'Entrevista reprogramada'), ('reminder_24h', 'Recordatorio 24h antes'), ('reminder_1h', 'Recordatorio 1h antes')], max_length=20, verbose_name='Tipo de notificación')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('is_read', models.BooleanField(default=False, verbose_name='Leída')),
                ('is_email_sent', models.BooleanField(default=False, verbose_name='Email enviado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='interviews.interview', verbose_name='Entrevista')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Notificación de Entrevista',
                'verbose_name_plural': 'Notificaciones de Entrevistas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewRescheduleRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='Razón de la reprogramación')),
                ('proposed_date', models.DateField(verbose_name='Nueva fecha propuesta')),
                ('proposed_time', models.TimeField(verbose_name='Nueva hora propuesta')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('accepted', 'Aceptada'), ('rejected', 'Rechazada')], default='pending', max_length=20, verbose_name='Estado')),
                ('response', models.TextField(blank=True, verbose_name='Respuesta')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reschedule_requests', to='interviews.interview', verbose_name='Entrevista')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reschedule_requests', to=settings.AUTH_USER_MODEL, verbose_name='Solicitado por')),
            ],
            options={
                'verbose_name': 'Solicitud de Reprogramación',
                'verbose_name_plural': 'Solicitudes de Reprogramación',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='interview',
            index=models.Index(fields=['company', 'scheduled_date'], name='interviews__company_509bcf_idx'),
        ),
        migrations.AddIndex(
            model_name='interview',
            index=models.Index(fields=['candidate', 'scheduled_date'], name='interviews__candida_464e78_idx'),
        ),
        migrations.AddIndex(
            model_name='interview',
            index=models.Index(fields=['status'], name='interviews__status_187f27_idx'),
        ),
    ]
